// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBnsaz9144E6FQBvP-TxAG_gKqyV_WjXA',
    appId: '1:451646551892:web:1df9b0fdd8101988f0bac1',
    messagingSenderId: '451646551892',
    projectId: 'e-tailor-ed19b',
    authDomain: 'e-tailor-ed19b.firebaseapp.com',
    storageBucket: 'e-tailor-ed19b.firebasestorage.app',
    measurementId: 'G-FKDD71TGXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOfaP6StgsuG8lMF584fhjaF8Y1gnHMgY',
    appId: '1:451646551892:android:db5d49a513ccec83f0bac1',
    messagingSenderId: '451646551892',
    projectId: 'e-tailor-ed19b',
    storageBucket: 'e-tailor-ed19b.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfaZ_74i_155L-xajCqOp57rrqU_wFYA',
    appId: '1:451646551892:ios:5b41e2c3c015d16df0bac1',
    messagingSenderId: '451646551892',
    projectId: 'e-tailor-ed19b',
    storageBucket: 'e-tailor-ed19b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHfaZ_74i_155L-xajCqOp57rrqU_wFYA',
    appId: '1:451646551892:ios:5b41e2c3c015d16df0bac1',
    messagingSenderId: '451646551892',
    projectId: 'e-tailor-ed19b',
    storageBucket: 'e-tailor-ed19b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBnsaz9144E6FQBvP-TxAG_gKqyV_WjXA',
    appId: '1:451646551892:web:7cc0bf02f8838665f0bac1',
    messagingSenderId: '451646551892',
    projectId: 'e-tailor-ed19b',
    authDomain: 'e-tailor-ed19b.firebaseapp.com',
    storageBucket: 'e-tailor-ed19b.firebasestorage.app',
    measurementId: 'G-BJSTRRGS36',
  );
}
